#!/usr/bin/env python3
"""
consolidate.py — Multi-date Purchase Plan Consolidation

Reads all available daily Excel files (or query results from SQLite)
and combines them into a single comparison workbook with:
  - All Data: every item × every date (filterable)
  - Summary by Date: daily totals + trend chart
  - Day Changes: day-over-day deltas (green/red color coding)
  - Top Monthly Changes: biggest movers across the period

=== NETWORK / FILE PATH CONFIGURATION ===

  access_excel_path        — Where existing daily .xls files are stored
                             (the ones generated by MS Access previously)
                             Example: "N:\\PurchasePlan_Output"

  consolidated_output_path — Where to save the combined workbook
                             Example: ".\\output\\consolidated"

  db_path                  — SQLite database (alternative data source)
                             Example: ".\\data\\pp29_history.db"

=== USAGE ===
  python consolidate.py                              # All available dates
  python consolidate.py --source excel               # From .xls files only
  python consolidate.py --source db                  # From SQLite database
  python consolidate.py --dates 20260201,20260210    # Specific dates only
"""

import os
import sys
import re
import json
import argparse
import logging
from typing import Dict, List, Optional

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from excel_writer import write_consolidated_excel
from db import init_database, get_all_data_for_dates, get_dates_in_db


# ============================================================
# CONFIG
# ============================================================

def load_config(config_path: str = None) -> dict:
    if config_path and os.path.exists(config_path):
        with open(config_path, 'r') as f:
            return json.load(f)
    search = [
        os.path.join(os.path.dirname(os.path.dirname(__file__)), 'config.json'),
        os.path.join(os.getcwd(), 'config.json'),
    ]
    for p in search:
        if os.path.exists(p):
            with open(p, 'r') as f:
                return json.load(f)
    print("ERROR: config.json not found.")
    sys.exit(1)


# ============================================================
# EXCEL FILE READER (reads existing .xls from Access)
# ============================================================

def read_access_excel(filepath: str) -> List[Dict]:
    """
    Read a single MS Access-generated .xls file.

    Extracts data from Sheet4 (the pivot table), skipping header rows 1-8,
    reading from row 9 onwards where the actual data begins.

    NETWORK DRIVE PATH:
      filepath comes from the access_excel_path folder in config.json

    Returns list of row dicts with Date and all period columns.
    """
    import xlrd
    wb = xlrd.open_workbook(filepath)
    sh = wb.sheet_by_name('Sheet4')

    # Get column headers from row 8 (0-indexed: row 9 in Excel = index 8)
    headers = [str(sh.cell_value(8, c)) for c in range(sh.ncols)]

    rows = []
    last_subgroup = ''

    for r in range(9, sh.nrows):
        item = str(sh.cell_value(r, 1))
        if not item:
            continue

        subgrp = str(sh.cell_value(r, 0))
        if subgrp and subgrp.strip():
            last_subgroup = subgrp

        row = {
            'SubGroup': last_subgroup,
            'ItemCode': item,
            'Desc': str(sh.cell_value(r, 2)),
        }
        uprc = sh.cell_value(r, 3)
        row['UnitPrc'] = float(uprc) if uprc else 0.0

        for c, h in enumerate(headers):
            if c < 4:  # skip identity cols (handled above)
                continue
            val = sh.cell_value(r, c)
            try:
                row[h] = float(val) if val else 0.0
            except (ValueError, TypeError):
                row[h] = 0.0

        rows.append(row)

    return rows


def read_all_access_excels(folder_path: str, date_filter: List[str] = None) -> List[Dict]:
    """
    Read all Access-generated .xls files from a folder.

    Args:
        folder_path: NETWORK DRIVE PATH — where Access .xls files are stored
                     (from config.json → access_excel_path)
        date_filter: Optional list of YYYYMMDD dates to include

    Returns list of all rows with Date and DateSort added.
    """
    all_rows = []
    files = sorted([f for f in os.listdir(folder_path)
                    if f.startswith('PurchasePlan') and f.endswith('.xls')
                    and '~lock' not in f])

    for fname in files:
        m = re.search(r'(\d{8})', fname)
        if not m:
            continue
        date_str = m.group(1)

        if date_filter and date_str not in date_filter:
            continue

        date_display = f"{date_str[4:6]}/{date_str[6:8]}"
        filepath = os.path.join(folder_path, fname)
        print(f"  Reading: {fname}")

        try:
            rows = read_access_excel(filepath)
            for row in rows:
                row['Date'] = date_display
                row['DateSort'] = date_str
            all_rows.extend(rows)
        except Exception as e:
            print(f"  [WARN] Failed to read {fname}: {e}")

    return all_rows


# ============================================================
# MAIN
# ============================================================

def run_consolidate(
    config: dict,
    source: str = 'excel',
    date_filter: List[str] = None
) -> bool:
    """
    Run the full consolidation process.

    Args:
        config:      Configuration dict from config.json
        source:      'excel' to read .xls files, 'db' to use SQLite
        date_filter: Optional list of YYYYMMDD strings to include
    """
    # ═══════════════════════════════════════════════════════
    # PATH CONFIGURATION — Edit in config.json, not here
    # ═══════════════════════════════════════════════════════
    excel_folder = config.get('access_excel_path', '')
    output_dir = config['consolidated_output_path']
    db_path = config.get('db_path', '.\\data\\pp29_history.db')
    # ═══════════════════════════════════════════════════════

    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s [%(levelname)s] %(message)s'
    )
    logger = logging.getLogger(__name__)
    logger.info("=== PP29 Consolidation ===")

    all_rows = []
    period_keys = []

    if source == 'db':
        # ── Read from SQLite database ──
        logger.info(f"Source: SQLite database ({db_path})")
        conn = init_database(db_path)
        all_dates = get_dates_in_db(conn)
        if date_filter:
            all_dates = [d for d in all_dates if d in date_filter]

        if not all_dates:
            logger.error("No dates found in database. Run daily.py first.")
            conn.close()
            return False

        all_rows = get_all_data_for_dates(conn, all_dates)
        conn.close()

        # Unpivot into the format expected by write_consolidated_excel
        # (This is a simplified mapping — period data is already flat)
        logger.info(f"  Retrieved {len(all_rows)} rows")

    else:
        # ── Read from existing .xls files ──
        logger.info(f"Source: Excel files ({excel_folder})")
        all_rows = read_all_access_excels(excel_folder, date_filter)
        period_keys = ['1stpo', '1stprod', '1stcb', '1stcbAmt',
                       '2ndpo', '2ndprod', '2ndcb', '2ndcbAmt']
        logger.info(f"  Loaded {len(all_rows)} rows from Excel files")

    if not all_rows:
        logger.error("No data to consolidate.")
        return False

    # Get sorted dates
    dates = sorted(set(r.get('DateSort', r.get('Date', '')) for r in all_rows))
    month_label = f"{dates[0][:4]}-{dates[0][4:6]}" if dates else "Unknown"

    # Generate consolidated workbook
    output_file = write_consolidated_excel(
        all_rows, dates, period_keys, output_dir, month_label
    )
    logger.info(f"Consolidated workbook saved: {output_file}")
    return True


def main():
    parser = argparse.ArgumentParser(
        description='PP29 Multi-date Consolidation'
    )
    parser.add_argument(
        '--source', '-s',
        choices=['excel', 'db'],
        default='excel',
        help='Data source: existing .xls files or SQLite database'
    )
    parser.add_argument(
        '--dates', '-d',
        help='Comma-separated dates to include (YYYYMMDD). Default: all available',
        default=None
    )
    parser.add_argument(
        '--config', '-c',
        help='Path to config.json',
        default=None
    )

    args = parser.parse_args()

    date_filter = None
    if args.dates:
        date_filter = [d.strip() for d in args.dates.split(',')]

    config = load_config(args.config)
    success = run_consolidate(config, args.source, date_filter)
    sys.exit(0 if success else 1)


if __name__ == '__main__':
    main()
